import { baseAPIPath } from './../../config';
import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { Router } from '@angular/router';
import { of, throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';

@Injectable({
  providedIn: 'root',
})
export class HttpService {
  constructor(private readonly http: HttpClient) {}

  getAllCompaniesData() {
    // return this.http
    //   .get<any>(`${baseAPIPath}/AllCompanies`)
    //   .pipe(catchError(this.handleError));
    return of([
      {
        id: '3143',
        companyName: 'AstraZeneca PLC',
        rating: 'BBB',
        stockSymbol: 'AZN',
        sector: 'Pharmaceutical',
        eScore: '16',
        sScore: '4',
        gScore: '10',
        totalESGScore: '30',
        environmentalModel: {
          cO2_Emissions: '100120100',
          total_energy_usage: '1000000',
          renewable_energy_usage: '700000',
          green_energy_iniatiatives: '2',
          water_consumption: '3000',
          water_treatment_reuse: '100',
          total_waste: '25000',
          waste_recycling: '15000',
          pollution_prevention_iniatives: '1',
          pollution_remediation_efforts: '1',
          permits_delay: '2',
          green_buildings: '3',
          sustainability_awards: '1',
          environmental_certifications: '5',
          news_GHG_Emissions: 'Positive',
          news_Energy_Management: 'Positive',
          news_Water_Management: 'Positive',
          news_Waste_Management: 'Positive',
          news_Pollution_Management: 'Negative',
          news_Environmental_Compliance: 'Negative',
          news_Environmental_Opportunities: 'Positive',
          news_Environmental_Certifications: 'Positive',
        },
        socialModel: {
          layoff_hiring_rates: '20',
          employer_satisfaction_ratings: '70',
          safety_incidents: '3',
          gender_ratio: '60',
          board_director_diversity: '80',
          child_forced_labor: '0',
          data_breaches: '0',
          csR_spend_donations: '5',
          delayed_payments: '0',
          supply_chain_initiatives: '1',
          social_certifications: '3',
          news_Labor_Relations: '0',
          news_Health_Safety: '0',
          news_Diversity_Inclusion: '0',
          news_Human_Rights_Abuses: '0',
          news_Data_Privacy: 'Negative',
          news_CSR_Initiatives: '0',
          news_Supplier_Engagement: '0',
          news_Social_Certifications: '0',
        },
        governanceModel: {
          minority_investor_protection: '0',
          transparency_index: '60',
          lawsuits_Lawsuits: '3',
          sanctions_Sanctions: '1',
          accounting_errors: '0',
          government_certifications: '12',
          disaster_recovery_time: 'Medium',
          risk_management_capability: 'High',
          news_Stakeholder_Rights: 'Positive',
          news_Business_Transparency: 'Positive',
          news_Corporate_Compliance: '0',
          news_Government_Certifications: 'Positive',
          news_Business_Stability: 'Positive',
        },
      },
      {
        id: '0012',
        companyName: 'O’Reilly Automotive Inc',
        rating: 'A',
        stockSymbol: 'ORLY',
        sector: 'Automotive',
        eScore: '26',
        sScore: '9',
        gScore: '17',
        totalESGScore: '52',
        environmentalModel: {
          cO2_Emissions: '150120100',
          total_energy_usage: '9000000',
          renewable_energy_usage: '200000',
          green_energy_iniatiatives: '5',
          water_consumption: '1000',
          water_treatment_reuse: '10',
          total_waste: '30000',
          waste_recycling: '10000',
          pollution_prevention_iniatives: '5',
          pollution_remediation_efforts: '3',
          permits_delay: '3',
          green_buildings: '2',
          sustainability_awards: '3',
          environmental_certifications: '12',
          news_GHG_Emissions: 'Positive',
          news_Energy_Management: 'Positive',
          news_Water_Management: 'Positive',
          news_Waste_Management: 'Positive',
          news_Pollution_Management: '0',
          news_Environmental_Compliance: 'Negative',
          news_Environmental_Opportunities: 'Positive',
          news_Environmental_Certifications: 'Positive',
        },
        socialModel: {
          layoff_hiring_rates: '30',
          employer_satisfaction_ratings: '75',
          safety_incidents: '15',
          gender_ratio: '70',
          board_director_diversity: '60',
          child_forced_labor: '0',
          data_breaches: '0',
          csR_spend_donations: '6',
          delayed_payments: '0',
          supply_chain_initiatives: '3',
          social_certifications: '5',
          news_Labor_Relations: '0',
          news_Health_Safety: '0',
          news_Diversity_Inclusion: '0',
          news_Human_Rights_Abuses: '0',
          news_Data_Privacy: '0',
          news_CSR_Initiatives: '0',
          news_Supplier_Engagement: 'Negative',
          news_Social_Certifications: '0',
        },
        governanceModel: {
          minority_investor_protection: '1',
          transparency_index: '70',
          lawsuits_Lawsuits: '0',
          sanctions_Sanctions: '0',
          accounting_errors: '0',
          government_certifications: '15',
          disaster_recovery_time: 'High',
          risk_management_capability: 'Medium',
          news_Stakeholder_Rights: 'Positive',
          news_Business_Transparency: 'Positive',
          news_Corporate_Compliance: 'Positive',
          news_Government_Certifications: 'Positive',
          news_Business_Stability: 'Positive',
        },
      },
      {
        id: '7624',
        companyName: 'Microsoft',
        rating: 'AA',
        stockSymbol: 'MFST',
        sector: 'Technology',
        eScore: '15',
        sScore: '33',
        gScore: '15',
        totalESGScore: '63',
        environmentalModel: {
          cO2_Emissions: '70000',
          total_energy_usage: '800000',
          renewable_energy_usage: '100000',
          green_energy_iniatiatives: '5',
          water_consumption: '1000',
          water_treatment_reuse: '10',
          total_waste: '30000',
          waste_recycling: '10000',
          pollution_prevention_iniatives: '5',
          pollution_remediation_efforts: '3',
          permits_delay: '3',
          green_buildings: '2',
          sustainability_awards: '3',
          environmental_certifications: '12',
          news_GHG_Emissions: 'Positive',
          news_Energy_Management: 'Positive',
          news_Water_Management: 'Positive',
          news_Waste_Management: 'Positive',
          news_Pollution_Management: '0',
          news_Environmental_Compliance: 'Negative',
          news_Environmental_Opportunities: 'Positive',
          news_Environmental_Certifications: 'Positive',
        },
        socialModel: {
          layoff_hiring_rates: '30',
          employer_satisfaction_ratings: '75',
          safety_incidents: '15',
          gender_ratio: '70',
          board_director_diversity: '60',
          child_forced_labor: '0',
          data_breaches: '8',
          csR_spend_donations: '6',
          delayed_payments: '0',
          supply_chain_initiatives: '3',
          social_certifications: '5',
          news_Labor_Relations: '0',
          news_Health_Safety: '0',
          news_Diversity_Inclusion: '0',
          news_Human_Rights_Abuses: '0',
          news_Data_Privacy: 'Positive',
          news_CSR_Initiatives: '0',
          news_Supplier_Engagement: 'Negative',
          news_Social_Certifications: '0',
        },
        governanceModel: {
          minority_investor_protection: '1',
          transparency_index: '70',
          lawsuits_Lawsuits: '0',
          sanctions_Sanctions: '0',
          accounting_errors: '0',
          government_certifications: '15',
          disaster_recovery_time: 'High',
          risk_management_capability: 'Medium',
          news_Stakeholder_Rights: 'Positive',
          news_Business_Transparency: 'Positive',
          news_Corporate_Compliance: 'Positive',
          news_Government_Certifications: 'Positive',
          news_Business_Stability: 'Positive',
        },
      },
      {
        id: '6723',
        companyName: 'Fiserv',
        rating: 'AA',
        stockSymbol: 'FISV',
        sector: 'Financial Services',
        eScore: '15',
        sScore: '26',
        gScore: '27',
        totalESGScore: '68',
        environmentalModel: {
          cO2_Emissions: '20000',
          total_energy_usage: '10000',
          renewable_energy_usage: '0',
          green_energy_iniatiatives: '5',
          water_consumption: '500',
          water_treatment_reuse: '0',
          total_waste: '500',
          waste_recycling: '200',
          pollution_prevention_iniatives: '5',
          pollution_remediation_efforts: '3',
          permits_delay: '3',
          green_buildings: '2',
          sustainability_awards: '3',
          environmental_certifications: '12',
          news_GHG_Emissions: 'Positive',
          news_Energy_Management: 'Positive',
          news_Water_Management: 'Positive',
          news_Waste_Management: 'Positive',
          news_Pollution_Management: '0',
          news_Environmental_Compliance: 'Negative',
          news_Environmental_Opportunities: 'Positive',
          news_Environmental_Certifications: 'Positive',
        },
        socialModel: {
          layoff_hiring_rates: '30',
          employer_satisfaction_ratings: '75',
          safety_incidents: '15',
          gender_ratio: '70',
          board_director_diversity: '60',
          child_forced_labor: '0',
          data_breaches: '8',
          csR_spend_donations: '6',
          delayed_payments: '0',
          supply_chain_initiatives: '3',
          social_certifications: '5',
          news_Labor_Relations: '0',
          news_Health_Safety: '0',
          news_Diversity_Inclusion: '0',
          news_Human_Rights_Abuses: '0',
          news_Data_Privacy: 'Positive',
          news_CSR_Initiatives: '0',
          news_Supplier_Engagement: 'Negative',
          news_Social_Certifications: '0',
        },
        governanceModel: {
          minority_investor_protection: '1',
          transparency_index: '70',
          lawsuits_Lawsuits: '0',
          sanctions_Sanctions: '0',
          accounting_errors: '0',
          government_certifications: '15',
          disaster_recovery_time: 'High',
          risk_management_capability: 'Medium',
          news_Stakeholder_Rights: 'Positive',
          news_Business_Transparency: 'Positive',
          news_Corporate_Compliance: 'Positive',
          news_Government_Certifications: 'Positive',
          news_Business_Stability: 'Positive',
        },
      },
      {
        id: '0980',
        companyName: 'Xcel Energy Inc',
        rating: 'A',
        stockSymbol: 'XEL',
        sector: 'Energy',
        eScore: '25',
        sScore: '4',
        gScore: '15',
        totalESGScore: '44',
        environmentalModel: {
          cO2_Emissions: '200000000',
          total_energy_usage: '20000000',
          renewable_energy_usage: '1000000',
          green_energy_iniatiatives: '2',
          water_consumption: '40000',
          water_treatment_reuse: '2000',
          total_waste: '25000',
          waste_recycling: '0',
          pollution_prevention_iniatives: '5',
          pollution_remediation_efforts: '3',
          permits_delay: '3',
          green_buildings: '2',
          sustainability_awards: '3',
          environmental_certifications: '12',
          news_GHG_Emissions: 'Positive',
          news_Energy_Management: 'Positive',
          news_Water_Management: 'Positive',
          news_Waste_Management: 'Positive',
          news_Pollution_Management: '0',
          news_Environmental_Compliance: 'Negative',
          news_Environmental_Opportunities: 'Positive',
          news_Environmental_Certifications: 'Positive',
        },
        socialModel: {
          layoff_hiring_rates: '30',
          employer_satisfaction_ratings: '75',
          safety_incidents: '15',
          gender_ratio: '70',
          board_director_diversity: '60',
          child_forced_labor: '0',
          data_breaches: '0',
          csR_spend_donations: '6',
          delayed_payments: '0',
          supply_chain_initiatives: '3',
          social_certifications: '5',
          news_Labor_Relations: '0',
          news_Health_Safety: '0',
          news_Diversity_Inclusion: '0',
          news_Human_Rights_Abuses: 'Negative',
          news_Data_Privacy: '0',
          news_CSR_Initiatives: '0',
          news_Supplier_Engagement: 'Negative',
          news_Social_Certifications: '0',
        },
        governanceModel: {
          minority_investor_protection: '1',
          transparency_index: '70',
          lawsuits_Lawsuits: '0',
          sanctions_Sanctions: '0',
          accounting_errors: '0',
          government_certifications: '15',
          disaster_recovery_time: 'High',
          risk_management_capability: 'Medium',
          news_Stakeholder_Rights: 'Positive',
          news_Business_Transparency: 'Positive',
          news_Corporate_Compliance: 'Positive',
          news_Government_Certifications: 'Positive',
          news_Business_Stability: 'Positive',
        },
      },
    ]);
  }

  handleError(error: HttpErrorResponse) {
    return throwError(error);
  }
}
